[project]
name = "soccer-zulip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "zulip>=0.9.1",
    "zulip-bots>=0.9.1",
]
